SELECT DISTINCT TABLE_SCHEMA 
FROM INFORMATION_SCHEMA.COLUMNS;

SELECT DISTINCT TABLE_SCHEMA, TABLE_NAME
FROM INFORMATION_SCHEMA.COLUMNS;
 
SELECT DISTINCT TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA='WarpAdmin2017';
 
SELECT *
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA='WarpAdmin2017';

USE WarpAdmin2017;


SHOW CREATE TABLE WarpAdmin2017.Entity; 

/*
CREATE TABLE `Entity` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `RecordStatusID` bigint(20) DEFAULT '10',
  `CreateDate` datetime DEFAULT CURRENT_TIMESTAMP,
  `AuID` bigint(20) DEFAULT '-1',
  `IuID` bigint(20) DEFAULT '-1',
  `LastModifyDate` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `LastAuID` bigint(20) DEFAULT '-1',
  `LastIuID` bigint(20) DEFAULT '-1',
  `EntityTypeID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8
*/

