DROP DATABASE IF EXISTS WarpSec_CN;
CREATE DATABASE WarpSec_CN CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE Parameters (
	ID 									BIGINT PRIMARY KEY AUTO_INCREMENT,
    RecordStatusID						BIGINT DEFAULT 10, 
    CreateDate 							DATETIME DEFAULT CURRENT_TIMESTAMP,
    AuID 								BIGINT DEFAULT -1,
	IuID 								BIGINT DEFAULT -1,
	LastModifyDate 						DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	LastAuID 							BIGINT DEFAULT -1,
	LastIuID 							BIGINT DEFAULT -1,
    WarpKey								NVARCHAR(255), 
    WarpValue							NVARCHAR(2000)
);



/* 

Environments

	TEST_CN
    TEST_US
    UAT_CN
    UAT_US
    PROD_CN
    PROD_US


*/